[tool.black]
line-length = 80
target-version = ['py311']

[tool.mypy]
namespace_packages = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_unreachable = true

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
