[tool.isort]
multi_line_output = 3 # https://pycqa.github.io/isort/docs/configuration/multi_line_output_modes.html
include_trailing_comma = true

[tool.black]
line-length = 80
target-version = ['py313']

[tool.mypy]
namespace_packages = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_unreachable = true

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
