# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui',
# licensing of 'MainForm.ui' applies.
#
# Created: Sat Mar 16 21:02:51 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 761)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setSpacing(-1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pbDeleteExpense = QtWidgets.QPushButton(self.tab)
        self.pbDeleteExpense.setObjectName("pbDeleteExpense")
        self.horizontalLayout_8.addWidget(self.pbDeleteExpense)
        self.pbReload = QtWidgets.QPushButton(self.tab)
        self.pbReload.setObjectName("pbReload")
        self.horizontalLayout_8.addWidget(self.pbReload)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.twExpenses = ExpenseTreeWidget(self.tab)
        self.twExpenses.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twExpenses.setAlternatingRowColors(False)
        self.twExpenses.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twExpenses.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twExpenses.setObjectName("twExpenses")
        self.twExpenses.headerItem().setText(0, "1")
        self.twExpenses.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.twExpenses)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leExpenseUserInput = AutoCompleteEdit(self.tab)
        self.leExpenseUserInput.setObjectName("leExpenseUserInput")
        self.horizontalLayout.addWidget(self.leExpenseUserInput)
        self.btnAddExpense = QtWidgets.QPushButton(self.tab)
        self.btnAddExpense.setObjectName("btnAddExpense")
        self.horizontalLayout.addWidget(self.btnAddExpense)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leNewEnvelope = QtWidgets.QLineEdit(self.tab_2)
        self.leNewEnvelope.setObjectName("leNewEnvelope")
        self.horizontalLayout_2.addWidget(self.leNewEnvelope)
        self.btnAddEnvelope = QtWidgets.QPushButton(self.tab_2)
        self.btnAddEnvelope.setObjectName("btnAddEnvelope")
        self.horizontalLayout_2.addWidget(self.btnAddEnvelope)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(19)
        self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(0)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(19)
        self.verticalLayout_3.addWidget(self.tableWidget_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.twRules = QtWidgets.QTableWidget(self.tab_3)
        self.twRules.setColumnCount(3)
        self.twRules.setObjectName("twRules")
        self.twRules.setColumnCount(3)
        self.twRules.setRowCount(0)
        self.twRules.horizontalHeader().setStretchLastSection(False)
        self.twRules.verticalHeader().setVisible(False)
        self.twRules.verticalHeader().setDefaultSectionSize(19)
        self.verticalLayout_4.addWidget(self.twRules)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btnApplyRules = QtWidgets.QPushButton(self.tab_3)
        self.btnApplyRules.setObjectName("btnApplyRules")
        self.horizontalLayout_3.addWidget(self.btnApplyRules)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblWeeklyStats = QtWidgets.QLabel(self.tab_4)
        self.lblWeeklyStats.setObjectName("lblWeeklyStats")
        self.horizontalLayout_7.addWidget(self.lblWeeklyStats)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.twBusinessPlan = QtWidgets.QTableWidget(self.tab_4)
        self.twBusinessPlan.setColumnCount(6)
        self.twBusinessPlan.setObjectName("twBusinessPlan")
        self.twBusinessPlan.setColumnCount(6)
        self.twBusinessPlan.setRowCount(0)
        self.twBusinessPlan.horizontalHeader().setStretchLastSection(True)
        self.twBusinessPlan.verticalHeader().setVisible(False)
        self.twBusinessPlan.verticalHeader().setDefaultSectionSize(19)
        self.verticalLayout_5.addWidget(self.twBusinessPlan)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbItemType = QtWidgets.QComboBox(self.tab_4)
        self.cbItemType.setObjectName("cbItemType")
        self.horizontalLayout_4.addWidget(self.cbItemType)
        self.leNewBPItem = QtWidgets.QLineEdit(self.tab_4)
        self.leNewBPItem.setObjectName("leNewBPItem")
        self.horizontalLayout_4.addWidget(self.leNewBPItem)
        self.cbItemFrequency = QtWidgets.QComboBox(self.tab_4)
        self.cbItemFrequency.setObjectName("cbItemFrequency")
        self.horizontalLayout_4.addWidget(self.cbItemFrequency)
        self.pbAddBPItem = QtWidgets.QPushButton(self.tab_4)
        self.pbAddBPItem.setObjectName("pbAddBPItem")
        self.horizontalLayout_4.addWidget(self.pbAddBPItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.pbApplyPlan = QtWidgets.QPushButton(self.tab_4)
        self.pbApplyPlan.setObjectName("pbApplyPlan")
        self.horizontalLayout_5.addWidget(self.pbApplyPlan)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.btnAddExpense, QtCore.SIGNAL("clicked()"), MainWindow.addExpense)
        QtCore.QObject.connect(self.tableWidget_2, QtCore.SIGNAL("currentItemChanged(QTableWidgetItem*,QTableWidgetItem*)"), MainWindow.onSelectedEnvelopeChanged)
        QtCore.QObject.connect(self.leExpenseUserInput, QtCore.SIGNAL("returnPressed()"), MainWindow.addExpense)
        QtCore.QObject.connect(self.btnAddEnvelope, QtCore.SIGNAL("clicked()"), MainWindow.addEnvelope)
        QtCore.QObject.connect(self.leNewEnvelope, QtCore.SIGNAL("returnPressed()"), MainWindow.addEnvelope)
        QtCore.QObject.connect(self.btnApplyRules, QtCore.SIGNAL("clicked()"), MainWindow.applyRules)
        QtCore.QObject.connect(self.pbAddBPItem, QtCore.SIGNAL("clicked()"), MainWindow.addBusinessPlanItem)
        QtCore.QObject.connect(self.leNewBPItem, QtCore.SIGNAL("returnPressed()"), MainWindow.addBusinessPlanItem)
        QtCore.QObject.connect(self.pbApplyPlan, QtCore.SIGNAL("clicked()"), MainWindow.applyBusinessPlan)
        QtCore.QObject.connect(self.pbDeleteExpense, QtCore.SIGNAL("clicked()"), MainWindow.deleteExpense)
        QtCore.QObject.connect(self.pbReload, QtCore.SIGNAL("clicked()"), MainWindow.reloadValues)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Envelopes", None, -1))
        self.pbDeleteExpense.setText(QtWidgets.QApplication.translate("MainWindow", "Delete Expense", None, -1))
        self.pbReload.setText(QtWidgets.QApplication.translate("MainWindow", "Reload", None, -1))
        self.leExpenseUserInput.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Enter new expense here", None, -1))
        self.btnAddExpense.setText(QtWidgets.QApplication.translate("MainWindow", "Add expense", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Expenses", None, -1))
        self.leNewEnvelope.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Enter name for new envelope here", None, -1))
        self.btnAddEnvelope.setText(QtWidgets.QApplication.translate("MainWindow", "New envelope", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Expenses for selected envelope:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Envelopes", None, -1))
        self.btnApplyRules.setText(QtWidgets.QApplication.translate("MainWindow", "Apply rules", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "Rules", None, -1))
        self.lblWeeklyStats.setText(QtWidgets.QApplication.translate("MainWindow", "Weekly stats:", None, -1))
        self.pbAddBPItem.setText(QtWidgets.QApplication.translate("MainWindow", "Add item", None, -1))
        self.pbApplyPlan.setText(QtWidgets.QApplication.translate("MainWindow", "Apply plan", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("MainWindow", "Financial Plan", None, -1))

from controls.autocompleteedit import AutoCompleteEdit
from controls.expensetreewidget import ExpenseTreeWidget
